import os
import io
from loguru import logger


def export_as_txt(content: str, file_name: str = "result") -> str:
    os.makedirs("vector_db", exist_ok=True)
    output_path = f"vector_db/{file_name}_export.txt"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"Exported TXT: {output_path}")
    return output_path


def export_as_docx(content: str, file_name: str = "result") -> str:
    from docx import Document
    os.makedirs("vector_db", exist_ok=True)
    output_path = f"vector_db/{file_name}_export.docx"
    doc = Document()
    doc.add_heading("DocuMind AI — Generated Report", 0)
    for line in content.split("\n"):
        if line.strip():
            if line.startswith("## "):
                doc.add_heading(line[3:], 2)
            elif line.startswith("# "):
                doc.add_heading(line[2:], 1)
            else:
                doc.add_paragraph(line)
    doc.save(output_path)
    logger.info(f"Exported DOCX: {output_path}")
    return output_path


def export_as_pptx(content: str, title: str = "DocuMind AI Report") -> str:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    import textwrap

    os.makedirs("vector_db", exist_ok=True)
    output_path = "vector_db/export.pptx"

    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by DocuMind AI"

    sections = content.split("\n\n")
    for section in sections:
        if not section.strip():
            continue
        lines = section.strip().split("\n")
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = lines[0][:100] if lines else "Content"
        body = "\n".join(lines[1:]) if len(lines) > 1 else section
        tf = slide.placeholders[1].text_frame
        tf.text = body[:500]

    prs.save(output_path)
    logger.info(f"Exported PPTX: {output_path}")
    return output_path


def generate_excel_from_document(doc_text: str, question: str) -> bytes:
    import pandas as pd
    import io as _io
    from utils.llm_provider import get_shared_llm
    from langchain_core.prompts import PromptTemplate
    import json
    import re

    prompt = PromptTemplate(
        input_variables=["text", "question"],
        template="""Extract structured tabular data from this document for: {question}

Document: {text}

Return ONLY valid JSON array of objects. No explanation. No markdown.
Example: [{{"Column1": "Value1", "Column2": "Value2"}}, ...]
Make column names meaningful. Include all relevant data."""
    )

    try:
        llm = get_shared_llm(temperature=0)
        result = (prompt | llm).invoke({"text": doc_text[:3000], "question": question})
        content = result.content.strip()
        content = re.sub(r"```[a-z]*", "", content).replace("```", "").strip()

        start = content.find("[")
        end = content.rfind("]") + 1
        if start >= 0 and end > start:
            data = json.loads(content[start:end])
            df = pd.DataFrame(data)
            buf = _io.BytesIO()
            df.to_excel(buf, index=False, engine="openpyxl")
            return buf.getvalue()
    except Exception as e:
        logger.error(f"Excel generation error: {e}")

    lines = [l.strip() for l in doc_text.split("\n") if l.strip()]
    df = pd.DataFrame({"Content": lines[:100]})
    buf = _io.BytesIO()
    df.to_excel(buf, index=False)
    return buf.getvalue()
