[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 2000

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"
primaryColor = "#58a6ff"