[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 2000
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[theme]
base = "dark"
backgroundColor = "#04060f"
secondaryBackgroundColor = "#080b18"
textColor = "#e2e8f0"
primaryColor = "#6366f1"